### ISSUE TITLE
Update of dependencies need a minor change in the config

### ISSUE THREAD

**Issue by acroyear** [matteofumagalli1275/nw-react-template#2]
If you want to be more up to date with the latest libs, after running "npm-check-updates" to get your package.json to the latest, you'll need to make the change in webpack.config.js to account for the change in the CopyPlugin's API. (the array needs to be wrapped as the patterns property of a pojo).

`    plugins: [
        new CopyPlugin({patterns: [{
            from: 'src/template-res',
            to: './'
        }]})
    ],`

With this, things should continue to work well with the latest in babel, react, material-ui.

(side note: also, I found that to get dev mode to work with debugging, I needed to install the SDK version of nw directly into the project. Having it globally didn't do the trick.)

**Comment by matteofumagalli1275** [comment]
Fixed
